package com.nebulastrike.game

/**
 * 7 Unique Master Player Starships with specialized abilities, missile launchers, continuous lasers, and dual wingman drones.
 */
data class PlayerShipInfo(
    val num: Int,
    val name: String,
    val id: String,
    val diff: String,
    val power: Int,
    val energy: Int,
    val speed: Int,
    val durability: Int,
    val health: Int,
    val cost: Int,
    val skill: String,
    val hasMissiles: Boolean = true,
    val hasLaser: Boolean = false,
    val hasDrones: Boolean = false,
    val weaponDesc: String = ""
)

val ALL_7_PLAYER_SHIPS = listOf(
    PlayerShipInfo(
        num = 1,
        name = "STAR-BLASTER",
        id = "ship-01",
        diff = "BALANCED",
        power = 4,
        energy = 5,
        speed = 5,
        durability = 3,
        health = 100,
        cost = 0,
        skill = "rapid-blaster + micro-missiles",
        hasMissiles = true,
        hasLaser = false,
        hasDrones = false,
        weaponDesc = "Twin Rapid Plasma Blasters + Auto Homing Micro-Missiles every 10s"
    ),
    PlayerShipInfo(
        num = 2,
        name = "ION-LANCER",
        id = "ship-02",
        diff = "PIERCING",
        power = 6,
        energy = 7,
        speed = 4,
        durability = 4,
        health = 140,
        cost = 1500,
        skill = "continuous-ion-laser",
        hasMissiles = false,
        hasLaser = true,
        hasDrones = false,
        weaponDesc = "Continuous Forward Piercing Ion Laser Beam + Side Pulse Cannons"
    ),
    PlayerShipInfo(
        num = 3,
        name = "VALKYRIE-WING",
        id = "ship-03",
        diff = "ESCORT SQUAD",
        power = 6,
        energy = 6,
        speed = 5,
        durability = 5,
        health = 180,
        cost = 3500,
        skill = "dual-wingman-drones",
        hasMissiles = true,
        hasLaser = false,
        hasDrones = true,
        weaponDesc = "Dual Side-by-Side Satellite Drone Attachments + Triple Autocannon"
    ),
    PlayerShipInfo(
        num = 4,
        name = "NOVA-BARRAGE",
        id = "ship-04",
        diff = "ARTILLERY",
        power = 8,
        energy = 6,
        speed = 3,
        durability = 7,
        health = 240,
        cost = 6500,
        skill = "heavy-missile-swarm",
        hasMissiles = true,
        hasLaser = false,
        hasDrones = false,
        weaponDesc = "Heavy Guided Missile Swarm (4 Rockets every 8s) + Wide Quad Flak"
    ),
    PlayerShipInfo(
        num = 5,
        name = "TEMPEST-TITAN",
        id = "ship-05",
        diff = "LIGHTNING",
        power = 9,
        energy = 8,
        speed = 4,
        durability = 7,
        health = 300,
        cost = 10000,
        skill = "continuous-arc-lightning",
        hasMissiles = true,
        hasLaser = true,
        hasDrones = false,
        weaponDesc = "Continuous Chain Lightning Discharge + High-Caliber Heavy Railguns"
    ),
    PlayerShipInfo(
        num = 6,
        name = "CHRONO-PHANTOM",
        id = "ship-06",
        diff = "STEALTH MIRAGE",
        power = 9,
        energy = 9,
        speed = 8,
        durability = 6,
        health = 350,
        cost = 16000,
        skill = "tachyon-drones + torpedoes",
        hasMissiles = true,
        hasLaser = false,
        hasDrones = true,
        weaponDesc = "Dual Stealth Drones + Hyper-Velocity Tachyon Streams + Quantum Torpedoes"
    ),
    PlayerShipInfo(
        num = 7,
        name = "OMEGA-DREADNOUGHT",
        id = "ship-07",
        diff = "SUPREME ARSENAL",
        power = 12,
        energy = 10,
        speed = 6,
        durability = 9,
        health = 500,
        cost = 25000,
        skill = "omega-core + drones + nukes",
        hasMissiles = true,
        hasLaser = true,
        hasDrones = true,
        weaponDesc = "Continuous Core Beam + Dual Flanking Gunships + Homing Nukes every 8s"
    )
)

val ALL_100_PLAYER_SHIPS = ALL_7_PLAYER_SHIPS
